from __future__ import annotations
from .utils import load
SPECIAL={
 'COMMERCIAL_EXPOSURE':['C04_COMMERCIAL_FINANCIAL','C07_LEGAL_PROCUREMENT_COMPLIANCE','C09_CAUSAL_SCENARIO'],
 'BOQ_INTELLIGENCE':['C04_COMMERCIAL_FINANCIAL','C05_DELIVERY_OPERATING','C09_CAUSAL_SCENARIO'],
 'SCOPE_ARCHITECTURE':['C05_DELIVERY_OPERATING'],'DELIVERY_JOURNEY':['C05_DELIVERY_OPERATING'],
 'TEAM_CAPACITY':['C05_DELIVERY_OPERATING','C08_PEOPLE_CAPABILITY_CHANGE'],'TECHNICAL_REQUIREMENTS':['C06_TECH_DATA_CYBER'],
 'QUALIFICATION_EVIDENCE':['C02_CLIENT_EVALUATOR_INTENT','C07_LEGAL_PROCUREMENT_COMPLIANCE'],'EVALUATION_WIN':['C02_CLIENT_EVALUATOR_INTENT','C04_COMMERCIAL_FINANCIAL'],
 'CLARIFICATIONS':['C02_CLIENT_EVALUATOR_INTENT','C07_LEGAL_PROCUREMENT_COMPLIANCE','C09_CAUSAL_SCENARIO'],'ASSUMPTIONS_GAPS':['C03_EPISTEMIC_TRUTH','C09_CAUSAL_SCENARIO'],
 'RISKS':['C04_COMMERCIAL_FINANCIAL','C05_DELIVERY_OPERATING','C07_LEGAL_PROCUREMENT_COMPLIANCE','C09_CAUSAL_SCENARIO'],
 'MANAGEMENT_DECISION':['C01_STRATEGIC_THESIS','C02_CLIENT_EVALUATOR_INTENT','C04_COMMERCIAL_FINANCIAL','C05_DELIVERY_OPERATING','C07_LEGAL_PROCUREMENT_COMPLIANCE','C09_CAUSAL_SCENARIO'],
 'COMPETITION_NARRATIVE':['C01_STRATEGIC_THESIS','C02_CLIENT_EVALUATOR_INTENT'],'OPPORTUNITY_SNAPSHOT':['C01_STRATEGIC_THESIS','C02_CLIENT_EVALUATOR_INTENT'],'STRATEGIC_READING':['C01_STRATEGIC_THESIS','C02_CLIENT_EVALUATOR_INTENT']}

def route(role:str, critical=True, rendered=False, deck=False, final_release=False):
    ordered=[]
    def add(x):
        if x not in ordered: ordered.append(x)
    if role not in ('COVER','TABLE_OF_CONTENTS'): add('C01_STRATEGIC_THESIS')
    add('C03_EPISTEMIC_TRUTH')
    for x in SPECIAL.get(role,[]): add(x)
    if role not in ('COVER','TABLE_OF_CONTENTS'): add('C10_ARTIFACT_SYNTHESIS')
    if rendered: add('C11_VISUAL_PERCEPTION'); add('C12_PRODUCTION_INTEGRITY')
    if critical: add('C13_ADVERSARIAL_COUNTERFACTUAL')
    if deck: add('C14_CROSS_DECK_NARRATIVE')
    if critical: add('C15_META_COGNITION_INTEGRITY')
    if final_release: add('C16_RELEASE_TRUTHFULNESS')
    return ordered

def validate_route(route_ids, contracts_path):
    data=load(contracts_path); known={x['id'] for x in data['councils']}; missing=[x for x in route_ids if x not in known]
    return {'status':'PASS' if not missing else 'FAIL','missing':missing,'route':route_ids}
